#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : at-spi2-core
Version  : 2.30.1
Release  : 22
URL      : https://download.gnome.org/sources/at-spi2-core/2.30/at-spi2-core-2.30.1.tar.xz
Source0  : https://download.gnome.org/sources/at-spi2-core/2.30/at-spi2-core-2.30.1.tar.xz
Summary  : Protocol definitions and daemon for D-Bus at-spi
Group    : Development/Tools
License  : LGPL-2.0
Requires: at-spi2-core-data = %{version}-%{release}
Requires: at-spi2-core-lib = %{version}-%{release}
Requires: at-spi2-core-libexec = %{version}-%{release}
Requires: at-spi2-core-license = %{version}-%{release}
Requires: at-spi2-core-locales = %{version}-%{release}
Requires: at-spi2-core-services = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : dbus-dev32
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glib-dev
BuildRequires : glib-dev32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : libSM-dev32
BuildRequires : libxkbcommon-dev
BuildRequires : libxkbcommon-dev32
BuildRequires : pkgconfig(32ice)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xi)
BuildRequires : pkgconfig(32xt)
BuildRequires : pkgconfig(32xtst)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xt)
BuildRequires : pkgconfig(xtst)

%description
D-Bus AT-SPI
------------
This version of at-spi is a major break from version 1.x.
It has been completely rewritten to use D-Bus rather than
ORBIT / CORBA for its transport protocol.

%package data
Summary: data components for the at-spi2-core package.
Group: Data

%description data
data components for the at-spi2-core package.


%package dev
Summary: dev components for the at-spi2-core package.
Group: Development
Requires: at-spi2-core-lib = %{version}-%{release}
Requires: at-spi2-core-data = %{version}-%{release}
Provides: at-spi2-core-devel = %{version}-%{release}
Requires: at-spi2-core = %{version}-%{release}

%description dev
dev components for the at-spi2-core package.


%package dev32
Summary: dev32 components for the at-spi2-core package.
Group: Default
Requires: at-spi2-core-lib32 = %{version}-%{release}
Requires: at-spi2-core-data = %{version}-%{release}
Requires: at-spi2-core-dev = %{version}-%{release}

%description dev32
dev32 components for the at-spi2-core package.


%package lib
Summary: lib components for the at-spi2-core package.
Group: Libraries
Requires: at-spi2-core-data = %{version}-%{release}
Requires: at-spi2-core-libexec = %{version}-%{release}
Requires: at-spi2-core-license = %{version}-%{release}

%description lib
lib components for the at-spi2-core package.


%package lib32
Summary: lib32 components for the at-spi2-core package.
Group: Default
Requires: at-spi2-core-data = %{version}-%{release}
Requires: at-spi2-core-license = %{version}-%{release}

%description lib32
lib32 components for the at-spi2-core package.


%package libexec
Summary: libexec components for the at-spi2-core package.
Group: Default
Requires: at-spi2-core-license = %{version}-%{release}

%description libexec
libexec components for the at-spi2-core package.


%package license
Summary: license components for the at-spi2-core package.
Group: Default

%description license
license components for the at-spi2-core package.


%package locales
Summary: locales components for the at-spi2-core package.
Group: Default

%description locales
locales components for the at-spi2-core package.


%package services
Summary: services components for the at-spi2-core package.
Group: Systemd services

%description services
services components for the at-spi2-core package.


%prep
%setup -q -n at-spi2-core-2.30.1
pushd ..
cp -a at-spi2-core-2.30.1 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551715586
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir
pushd ../build32
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="$ASFLAGS --32"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
meson --libdir=/usr/lib32 --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir
popd

%install
mkdir -p %{buildroot}/usr/share/package-licenses/at-spi2-core
cp COPYING %{buildroot}/usr/share/package-licenses/at-spi2-core/COPYING
pushd ../build32
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang at-spi2-core

%files
%defattr(-,root,root,-)
/usr/lib32/girepository-1.0/Atspi-2.0.typelib

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Atspi-2.0.typelib
/usr/share/dbus-1/accessibility-services/org.a11y.atspi.Registry.service
/usr/share/dbus-1/services/org.a11y.Bus.service
/usr/share/defaults/at-spi2/accessibility.conf
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/at-spi-2.0/atspi/atspi-accessible.h
/usr/include/at-spi-2.0/atspi/atspi-action.h
/usr/include/at-spi-2.0/atspi/atspi-application.h
/usr/include/at-spi-2.0/atspi/atspi-collection.h
/usr/include/at-spi-2.0/atspi/atspi-component.h
/usr/include/at-spi-2.0/atspi/atspi-constants.h
/usr/include/at-spi-2.0/atspi/atspi-device-listener.h
/usr/include/at-spi-2.0/atspi/atspi-document.h
/usr/include/at-spi-2.0/atspi/atspi-editabletext.h
/usr/include/at-spi-2.0/atspi/atspi-enum-types.h
/usr/include/at-spi-2.0/atspi/atspi-event-listener.h
/usr/include/at-spi-2.0/atspi/atspi-gmain.h
/usr/include/at-spi-2.0/atspi/atspi-hyperlink.h
/usr/include/at-spi-2.0/atspi/atspi-hypertext.h
/usr/include/at-spi-2.0/atspi/atspi-image.h
/usr/include/at-spi-2.0/atspi/atspi-matchrule.h
/usr/include/at-spi-2.0/atspi/atspi-misc.h
/usr/include/at-spi-2.0/atspi/atspi-object.h
/usr/include/at-spi-2.0/atspi/atspi-registry.h
/usr/include/at-spi-2.0/atspi/atspi-relation.h
/usr/include/at-spi-2.0/atspi/atspi-selection.h
/usr/include/at-spi-2.0/atspi/atspi-stateset.h
/usr/include/at-spi-2.0/atspi/atspi-table-cell.h
/usr/include/at-spi-2.0/atspi/atspi-table.h
/usr/include/at-spi-2.0/atspi/atspi-text.h
/usr/include/at-spi-2.0/atspi/atspi-types.h
/usr/include/at-spi-2.0/atspi/atspi-value.h
/usr/include/at-spi-2.0/atspi/atspi.h
/usr/lib64/libatspi.so
/usr/lib64/pkgconfig/atspi-2.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libatspi.so
/usr/lib32/pkgconfig/32atspi-2.pc
/usr/lib32/pkgconfig/atspi-2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libatspi.so.0
/usr/lib64/libatspi.so.0.0.1

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libatspi.so.0
/usr/lib32/libatspi.so.0.0.1

%files libexec
%defattr(-,root,root,-)
/usr/libexec/at-spi-bus-launcher
/usr/libexec/at-spi2-registryd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/at-spi2-core/COPYING

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/at-spi-dbus-bus.service

%files locales -f at-spi2-core.lang
%defattr(-,root,root,-)

